import 'record_scope.dart';
import 'record_types.dart';

class CharacterRecordTypes {
  const CharacterRecordTypes._();

  static final RecordTypeDefinition character = RecordTypeDefinition(
    id: 'character',
    name: 'Character',
    description:
        'A canonical character shared by Character Studio and every connected AuthorOS view.',
    icon: 'person',
    categoryId: 'characters',
    baseTypeId: 'general-lore',
    fields: _fields,
    sections: _sections,
    suggestedLinkTypeIds: const [
      'appearsIn',
      'mentionedIn',
      'relatedTo',
      'parentOf',
      'memberOf',
      'livesIn',
      'bornIn',
      'owns',
      'uses',
      'pursues',
      'hasArc',
      'knows',
    ],
    templateVersion: 2,
    builtIn: true,
    sourcePackId: 'authoros-core',
    permissions: const {'editableDefinition': false},
    exportBehavior: const {'includeStructuredFields': true},
    extensionData: const {
      'studio': 'character',
      'supportsSparseProfiles': true,
      'authorKnowledgeSeparated': true,
    },
  );

  static final List<RecordTypeDefinition> templates = [
    _template(
      'character-basic',
      'Basic Character',
      visibleSections: const ['identity', 'appearance', 'personality', 'notes'],
    ),
    _template('character-main', 'Main Character'),
    _template(
      'character-supporting',
      'Supporting Character',
      visibleSections: const [
        'identity',
        'appearance',
        'personality',
        'backstory',
        'relationships',
        'storyRole',
        'goals',
        'notes',
      ],
    ),
    _template('character-antagonist', 'Antagonist'),
    _template('character-love-interest', 'Love Interest'),
    _template('character-villain', 'Villain'),
    _template('character-hero', 'Hero'),
    _template('character-pov', 'POV Character'),
    _template('character-fae', 'Fae Character'),
    _template('character-fantasy', 'Fantasy Character'),
    _template('character-modern', 'Modern Character'),
    _template('character-historical', 'Historical Character'),
  ];

  static RecordTypeDefinition customTemplate({
    required String id,
    required String name,
    required String projectId,
    List<RecordFieldDefinition> fields = const [],
    List<RecordTemplateSection> sections = const [],
    int templateVersion = 1,
  }) =>
      RecordTypeDefinition(
        id: id,
        name: name,
        description: 'Project-scoped custom character template.',
        icon: 'person_edit',
        categoryId: 'characters',
        baseTypeId: 'character',
        fields: fields,
        sections: sections,
        scopeType: RecordScopeType.project,
        scopeId: projectId,
        templateVersion: templateVersion,
        extensionData: const {'customCharacterTemplate': true},
      );
}

RecordTypeDefinition _template(
  String id,
  String name, {
  List<String>? visibleSections,
}) =>
    RecordTypeDefinition(
      id: id,
      name: name,
      description: '$name character template.',
      icon: 'person',
      categoryId: 'characters',
      baseTypeId: 'character',
      fields: const [],
      sections: const [],
      templateVersion: 1,
      builtIn: true,
      sourcePackId: 'authoros-character-core',
      extensionData: {
        if (visibleSections != null) 'visibleSections': visibleSections,
        'supportsSparseProfiles': true,
      },
    );

RecordFieldDefinition _field(
  String id,
  String label,
  RecordFieldType type,
  int order, {
  bool required = false,
  List<String> options = const [],
  List<String> referenceTypeIds = const [],
  String description = '',
}) =>
    RecordFieldDefinition(
      id: id,
      label: label,
      type: type,
      order: order,
      required: required,
      options: options,
      referenceTypeIds: referenceTypeIds,
      description: description,
    );

final List<RecordFieldDefinition> _fields = [
  _field(
      'identity.displayName', 'Display name', RecordFieldType.shortText, 100),
  _field('identity.fullName', 'Full name', RecordFieldType.shortText, 101,
      required: true),
  _field('identity.firstName', 'First name', RecordFieldType.shortText, 102),
  _field('identity.middleName', 'Middle name', RecordFieldType.shortText, 103),
  _field('identity.lastName', 'Last name', RecordFieldType.shortText, 104),
  _field('identity.aliases', 'Aliases', RecordFieldType.list, 105),
  _field('identity.nicknames', 'Nicknames', RecordFieldType.list, 106),
  _field('identity.titles', 'Titles and honorifics', RecordFieldType.list, 107),
  _field('identity.formerNames', 'Former names', RecordFieldType.list, 108),
  _field('identity.secretNames', 'Secret names', RecordFieldType.list, 109),
  _field('identity.codeNames', 'Code names', RecordFieldType.list, 110),
  _field('identity.knownAs', 'Known as', RecordFieldType.list, 111),
  _field('identity.pronouns', 'Pronouns', RecordFieldType.shortText, 112),
  _field('identity.gender', 'Gender', RecordFieldType.shortText, 113),
  _field('identity.age', 'Age', RecordFieldType.number, 114),
  _field('identity.dateOfBirth', 'Date of birth', RecordFieldType.date, 115),
  _field('identity.placeOfBirth', 'Place of birth',
      RecordFieldType.locationReference, 116,
      referenceTypeIds: const ['location', 'place']),
  _field('identity.species', 'Species', RecordFieldType.recordReference, 117,
      referenceTypeIds: const ['species', 'creature']),
  _field('identity.raceType', 'Race / type', RecordFieldType.shortText, 118),
  _field('identity.nationalityOrigin', 'Nationality / origin',
      RecordFieldType.shortText, 119),
  _field(
      'identity.occupation', 'Occupation', RecordFieldType.recordReference, 120,
      referenceTypeIds: const ['occupation']),
  _field('identity.roles', 'Roles', RecordFieldType.multipleChoice, 121,
      options: const [
        'Protagonist',
        'Antagonist',
        'Deuteragonist',
        'Supporting Character',
        'Love Interest',
        'Mentor',
        'Foil',
        'Rival',
        'Villain',
        'Hero',
        'Antihero',
        'Comic Relief',
        'Narrator',
        'POV Character',
        'Minor Character'
      ]),
  _field('identity.affiliations', 'Affiliations', RecordFieldType.list, 122),
  _field('identity.characterStatus', 'Character status',
      RecordFieldType.singleChoice, 123,
      options: const [
        'Alive',
        'Dead',
        'Missing',
        'Unknown',
        'Undead',
        'Transformed',
        'Retired',
        'Inactive',
        'Other'
      ]),
  _field('appearance.height', 'Height', RecordFieldType.shortText, 200),
  _field('appearance.build', 'Build', RecordFieldType.shortText, 201),
  _field('appearance.bodyType', 'Body type', RecordFieldType.shortText, 202),
  _field('appearance.hair', 'Hair', RecordFieldType.shortText, 203),
  _field(
      'appearance.hairTexture', 'Hair texture', RecordFieldType.shortText, 204),
  _field(
      'appearance.hairColour', 'Hair colour', RecordFieldType.shortText, 205),
  _field('appearance.eyeColour', 'Eye colour', RecordFieldType.shortText, 206),
  _field('appearance.skin', 'Skin', RecordFieldType.shortText, 207),
  _field('appearance.distinguishingFeatures', 'Distinguishing features',
      RecordFieldType.longText, 208),
  _field('appearance.scars', 'Scars', RecordFieldType.longText, 209),
  _field('appearance.tattoos', 'Tattoos', RecordFieldType.longText, 210),
  _field('appearance.birthmarks', 'Birthmarks', RecordFieldType.longText, 211),
  _field('appearance.piercings', 'Piercings', RecordFieldType.longText, 212),
  _field('appearance.limitations', 'Disabilities / limitations',
      RecordFieldType.longText, 213),
  _field('appearance.typicalClothing', 'Typical clothing',
      RecordFieldType.longText, 214),
  _field('appearance.formalClothing', 'Formal clothing',
      RecordFieldType.longText, 215),
  _field('appearance.combatClothing', 'Combat clothing',
      RecordFieldType.longText, 216),
  _field(
      'appearance.accessories', 'Accessories', RecordFieldType.longText, 217),
  _field('appearance.weapons', 'Weapons', RecordFieldType.list, 218),
  _field('appearance.physicalPresence', 'Physical presence',
      RecordFieldType.longText, 219),
  _field('appearance.voice', 'Voice', RecordFieldType.longText, 220),
  _field('appearance.accent', 'Accent', RecordFieldType.shortText, 221),
  _field('appearance.mannerisms', 'Mannerisms', RecordFieldType.longText, 222),
  _field('appearance.posture', 'Posture', RecordFieldType.shortText, 223),
  _field('appearance.movement', 'Movement', RecordFieldType.longText, 224),
  _field('appearance.scent', 'Scent', RecordFieldType.shortText, 225),
  _field('appearance.sensoryTraits', 'Other sensory traits',
      RecordFieldType.longText, 226),
  _field('personality.summary', 'Personality summary', RecordFieldType.longText,
      300),
  _field('personality.coreTraits', 'Core traits', RecordFieldType.list, 301),
  _field('personality.positiveTraits', 'Positive traits', RecordFieldType.list,
      302),
  _field('personality.negativeTraits', 'Negative traits', RecordFieldType.list,
      303),
  _field('personality.strengths', 'Strengths', RecordFieldType.list, 304),
  _field('personality.weaknesses', 'Weaknesses', RecordFieldType.list, 305),
  _field('personality.flaws', 'Flaws', RecordFieldType.list, 306),
  _field('personality.fears', 'Fears', RecordFieldType.list, 307),
  _field('personality.insecurities', 'Insecurities', RecordFieldType.list, 308),
  _field('personality.habits', 'Habits', RecordFieldType.list, 309),
  _field('personality.quirks', 'Quirks', RecordFieldType.list, 310),
  _field('personality.mannerisms', 'Mannerisms', RecordFieldType.list, 311),
  _field('personality.values', 'Values', RecordFieldType.list, 312),
  _field('personality.beliefs', 'Beliefs', RecordFieldType.list, 313),
  _field('personality.moralsEthics', 'Morals / ethics',
      RecordFieldType.longText, 314),
  _field('personality.boundaries', 'Boundaries', RecordFieldType.longText, 315),
  _field(
      'personality.temperament', 'Temperament', RecordFieldType.shortText, 316),
  _field('personality.emotionalBaseline', 'Emotional baseline',
      RecordFieldType.longText, 317),
  _field('personality.emotionalTriggers', 'Emotional triggers',
      RecordFieldType.list, 318),
  _field('personality.stressResponse', 'Stress response',
      RecordFieldType.longText, 319),
  _field('personality.copingMechanisms', 'Coping mechanisms',
      RecordFieldType.list, 320),
  _field('personality.senseOfHumour', 'Sense of humour',
      RecordFieldType.longText, 321),
  _field('personality.communicationStyle', 'Communication style',
      RecordFieldType.longText, 322),
  _field('personality.socialBehaviour', 'Social behaviour',
      RecordFieldType.longText, 323),
  _field(
      'personality.trustStyle', 'Trust style', RecordFieldType.shortText, 324),
  _field('personality.attachmentStyle', 'Attachment style',
      RecordFieldType.shortText, 325),
  _field('personality.conflictStyle', 'Conflict style',
      RecordFieldType.shortText, 326),
  _field('psychology.coreWound', 'Core wound', RecordFieldType.longText, 400),
  _field(
      'psychology.falseBelief', 'False belief', RecordFieldType.longText, 401),
  _field('psychology.coreBelief', 'Core belief', RecordFieldType.longText, 402),
  _field('psychology.internalNeed', 'Internal need', RecordFieldType.longText,
      403),
  _field('psychology.externalWant', 'External want', RecordFieldType.longText,
      404),
  _field('psychology.fear', 'Fear', RecordFieldType.longText, 405),
  _field('psychology.desire', 'Desire', RecordFieldType.longText, 406),
  _field('psychology.primaryMotivation', 'Primary motivation',
      RecordFieldType.longText, 407),
  _field('psychology.secondaryMotivations', 'Secondary motivations',
      RecordFieldType.list, 408),
  _field('psychology.emotionalNeeds', 'Emotional needs', RecordFieldType.list,
      409),
  _field('psychology.secrets', 'Secrets', RecordFieldType.list, 410),
  _field('psychology.shame', 'Shame', RecordFieldType.longText, 411),
  _field('psychology.guilt', 'Guilt', RecordFieldType.longText, 412),
  _field('psychology.regrets', 'Regrets', RecordFieldType.list, 413),
  _field('psychology.obsessions', 'Obsessions', RecordFieldType.list, 414),
  _field('psychology.avoidances', 'Avoidances', RecordFieldType.list, 415),
  _field('psychology.triggers', 'Triggers', RecordFieldType.list, 416),
  _field('psychology.defences', 'Defences', RecordFieldType.list, 417),
  _field(
      'psychology.contradictions', 'Contradictions', RecordFieldType.list, 418),
  _field('psychology.internalConflict', 'Internal conflict',
      RecordFieldType.longText, 419),
  _field('psychology.externalConflict', 'External conflict',
      RecordFieldType.longText, 420),
  _field('backstory.childhood', 'Childhood', RecordFieldType.longText, 500),
  _field('backstory.family', 'Family', RecordFieldType.longText, 501),
  _field('backstory.education', 'Education', RecordFieldType.longText, 502),
  _field('backstory.earlyExperiences', 'Early experiences',
      RecordFieldType.longText, 503),
  _field('backstory.majorLifeEvents', 'Major life events', RecordFieldType.list,
      504),
  _field('backstory.friendships', 'Friendships', RecordFieldType.longText, 505),
  _field('backstory.enemies', 'Enemies', RecordFieldType.longText, 506),
  _field('backstory.mentors', 'Mentors', RecordFieldType.longText, 507),
  _field('backstory.previousOccupations', 'Previous occupations',
      RecordFieldType.list, 508),
  _field('backstory.previousRelationships', 'Previous relationships',
      RecordFieldType.longText, 509),
  _field(
      'backstory.majorMistakes', 'Major mistakes', RecordFieldType.list, 510),
  _field('backstory.importantVictories', 'Important victories',
      RecordFieldType.list, 511),
  _field('backstory.importantLosses', 'Important losses', RecordFieldType.list,
      512),
  _field('backstory.secrets', 'Backstory secrets', RecordFieldType.list, 513),
  _field(
      'backstory.turningPoints', 'Turning points', RecordFieldType.list, 514),
  _field('goals.entries', 'Goals', RecordFieldType.table, 600,
      description:
          'Multiple typed goals with priority, motivation, obstacles, stakes, progress, status, deadline, and links.'),
  _field('goals.primaryGoal', 'Primary goal', RecordFieldType.longText, 601),
  _field('goals.motivation', 'Motivation', RecordFieldType.longText, 602),
  _field('goals.obstacles', 'Obstacles', RecordFieldType.longText, 603),
  _field('goals.stakes', 'Stakes', RecordFieldType.longText, 604),
  _field('arcs.entries', 'Character arcs', RecordFieldType.table, 700,
      description:
          'Multiple internal, external, emotional, relationship, moral, and belief arcs.'),
  _field('arcs.startingState', 'Starting state', RecordFieldType.longText, 701),
  _field(
      'arcs.incitingChange', 'Inciting change', RecordFieldType.longText, 702),
  _field('arcs.turningPoints', 'Turning points', RecordFieldType.list, 703),
  _field('arcs.lowestPoint', 'Lowest point', RecordFieldType.longText, 704),
  _field('arcs.majorChoices', 'Major choices', RecordFieldType.list, 705),
  _field('arcs.consequences', 'Consequences', RecordFieldType.list, 706),
  _field('arcs.endState', 'End state', RecordFieldType.longText, 707),
  _field('secrets.entries', 'Secrets', RecordFieldType.table, 800,
      description:
          'Structured secrets with knowledge, risk, consequence, reveal state, and stable references.'),
  _field('knowledge.entries', 'Character knowledge', RecordFieldType.table, 810,
      description:
          'What the character knows, does not know, suspects, believes, misunderstands, or has forgotten.'),
  _field('knowledge.authorNotes', 'Author knowledge', RecordFieldType.longText,
      811),
  _field('voice.speechStyle', 'Speech style', RecordFieldType.longText, 900),
  _field('voice.vocabulary', 'Vocabulary', RecordFieldType.longText, 901),
  _field('voice.sentenceLength', 'Sentence length', RecordFieldType.shortText,
      902),
  _field('voice.formality', 'Formality', RecordFieldType.shortText, 903),
  _field('voice.favouriteWords', 'Favourite words', RecordFieldType.list, 904),
  _field('voice.wordsNeverUsed', 'Words never used', RecordFieldType.list, 905),
  _field(
      'voice.swearingStyle', 'Swearing style', RecordFieldType.longText, 906),
  _field('voice.metaphors', 'Metaphors', RecordFieldType.longText, 907),
  _field('voice.catchphrases', 'Catchphrases', RecordFieldType.list, 908),
  _field(
      'voice.dialogueRhythm', 'Dialogue rhythm', RecordFieldType.longText, 909),
  _field(
      'voice.internalVoice', 'Internal voice', RecordFieldType.longText, 910),
  _field(
      'voice.emotionalVoice', 'Emotional voice', RecordFieldType.longText, 911),
  _field('voice.accent', 'Accent', RecordFieldType.shortText, 912),
  _field('voice.speechPatterns', 'Speech patterns', RecordFieldType.list, 913),
  _field('voice.dialogueExamples', 'Example dialogue', RecordFieldType.longText,
      914),
  _field('pov.enabled', 'POV enabled', RecordFieldType.boolean, 1000),
  _field('pov.priority', 'POV priority', RecordFieldType.number, 1001),
  _field(
      'pov.narrativeVoice', 'Narrative voice', RecordFieldType.longText, 1002),
  _field('pov.internalVoice', 'Internal voice', RecordFieldType.longText, 1003),
  _field('pov.sensoryBias', 'Sensory bias', RecordFieldType.longText, 1004),
  _field('pov.emotionalBias', 'Emotional bias', RecordFieldType.longText, 1005),
  _field('pov.knowledgeBoundaries', 'Knowledge boundaries',
      RecordFieldType.longText, 1006),
  _field('pov.narrativeReliability', 'Narrative reliability',
      RecordFieldType.shortText, 1007),
  _field('pov.typicalChapterLength', 'Typical chapter length',
      RecordFieldType.number, 1008),
  _field('pov.notes', 'POV notes', RecordFieldType.longText, 1009),
  _field('notes.general', 'General notes', RecordFieldType.longText, 1100),
  _field('notes.writer', 'Writer notes', RecordFieldType.longText, 1101),
  _field(
      'notes.development', 'Development notes', RecordFieldType.longText, 1102),
  _field(
      'notes.continuity', 'Continuity notes', RecordFieldType.longText, 1103),
  _field('notes.research', 'Research notes', RecordFieldType.longText, 1104),
  _field('notes.private', 'Private notes', RecordFieldType.longText, 1105),
  _field(
      'media.primaryPortrait', 'Primary portrait', RecordFieldType.image, 1200),
  _field(
      'media.referenceImages', 'Reference images', RecordFieldType.list, 1201),
];

final List<RecordTemplateSection> _sections = [
  _section('identity', 'Identity', 100),
  _section('appearance', 'Appearance', 200),
  _section('personality', 'Personality', 300),
  _section('psychology', 'Psychology', 400),
  _section('backstory', 'Backstory', 500),
  _section('goals', 'Goals and motivations', 600),
  _section('arcs', 'Character arcs', 700),
  _section('secrets', 'Secrets', 800),
  _section('knowledge', 'Knowledge', 810),
  _section('voice', 'Voice', 900),
  _section('pov', 'POV profile', 1000),
  _section('notes', 'Notes', 1100),
  _section('media', 'Portraits and references', 1200),
  ...[
    ('family', 'Family'),
    ('relationships', 'Relationships'),
    ('factions', 'Factions and organisations'),
    ('locations', 'Locations'),
    ('items', 'Items and possessions'),
    ('storyRole', 'Role in story'),
    ('timeline', 'Timeline'),
    ('manuscript', 'Manuscript appearances'),
    ('codex', 'Story Codex'),
    ('world', 'World'),
  ].indexed.map((entry) => RecordTemplateSection(
        id: entry.$2.$1,
        title: entry.$2.$2,
        order: 1300 + entry.$1,
        fieldIds: const [],
        collapsedByDefault: true,
        extensionData: const {'connectionBacked': true},
      )),
];

RecordTemplateSection _section(String id, String title, int order) =>
    RecordTemplateSection(
      id: id,
      title: title,
      order: order,
      fieldIds: _fields
          .where((field) => field.id.startsWith('$id.'))
          .map((field) => field.id)
          .toList(),
      collapsedByDefault: id != 'identity',
    );
