import 'record_types.dart';

class TimelineRecordTypes {
  const TimelineRecordTypes._();

  static const baseTypeId = 'timeline-record';
  static const eventTypeId = 'timeline-event';
  static const calendarTypeId = 'calendar-definition';

  static const List<String> recordTypeIds = [
    'timeline',
    'timeline-era',
    'timeline-age',
    'timeline-historical-period',
    'timeline-event',
    'timeline-event-group',
    'timeline-date',
    'timeline-date-range',
    'timeline-milestone',
    'timeline-turning-point',
    'timeline-historical-record',
    'timeline-war',
    'timeline-battle',
    'timeline-disaster',
    'timeline-political-event',
    'timeline-birth',
    'timeline-death',
    'timeline-discovery',
    'timeline-invention',
    'timeline-founding',
    'timeline-destruction',
    'timeline-migration',
    'timeline-journey',
    'timeline-relationship-event',
    'timeline-character-event',
    'timeline-world-event',
    'timeline-custom-event',
  ];

  static final List<RecordTypeDefinition> definitions = [
    _base,
    _calendar,
    ..._children,
  ];

  static final List<RecordTypeDefinition> _children = _timelineTypes.entries
      .map(
        (entry) => RecordTypeDefinition(
          id: entry.key,
          name: entry.value,
          description: '${entry.value} represented in Timeline Studio.',
          icon: _icons[entry.key] ?? 'event',
          categoryId: 'timeline',
          baseTypeId: baseTypeId,
          fields: const [],
          sections: const [],
          suggestedLinkTypeIds: const [
            'partOf',
            'before',
            'after',
            'occursAt',
            'involves',
            'relatedTo',
          ],
          builtIn: true,
          sourcePackId: 'authoros-core',
          permissions: const {'editableDefinition': false},
          extensionData: const {'timelineStudio': true},
        ),
      )
      .toList(growable: false);
}

const _base = RecordTypeDefinition(
  id: TimelineRecordTypes.baseTypeId,
  name: 'Timeline Record',
  description: 'A temporal record shared across AuthorOS studios.',
  icon: 'timeline',
  categoryId: 'timeline',
  baseTypeId: 'general-lore',
  fields: [
    RecordFieldDefinition(
      id: 'eventType',
      label: 'Event type',
      type: RecordFieldType.shortText,
      order: 100,
    ),
    RecordFieldDefinition(
      id: 'start',
      label: 'Start',
      type: RecordFieldType.table,
      order: 101,
      extensionData: {'temporalValue': true},
    ),
    RecordFieldDefinition(
      id: 'end',
      label: 'End',
      type: RecordFieldType.table,
      order: 102,
      extensionData: {'temporalValue': true},
    ),
    RecordFieldDefinition(
      id: 'duration',
      label: 'Duration',
      type: RecordFieldType.table,
      order: 103,
    ),
    RecordFieldDefinition(
      id: 'precision',
      label: 'Precision',
      type: RecordFieldType.singleChoice,
      order: 104,
      defaultValue: 'unknown',
      options: ['exact', 'approximate', 'range', 'relative', 'unknown'],
    ),
    RecordFieldDefinition(
      id: 'temporalStatus',
      label: 'Status',
      type: RecordFieldType.shortText,
      order: 105,
    ),
    RecordFieldDefinition(
      id: 'importance',
      label: 'Importance',
      type: RecordFieldType.singleChoice,
      order: 106,
      defaultValue: 'normal',
      options: ['minor', 'normal', 'important', 'major', 'critical'],
    ),
    RecordFieldDefinition(
      id: 'temporalScope',
      label: 'Scope',
      type: RecordFieldType.shortText,
      order: 107,
    ),
    RecordFieldDefinition(
      id: 'dateRepresentations',
      label: 'Calendar representations',
      type: RecordFieldType.table,
      order: 108,
      extensionData: {'stableIds': true},
    ),
    RecordFieldDefinition(
      id: 'relativeDate',
      label: 'Relative date',
      type: RecordFieldType.table,
      order: 109,
      extensionData: {'stableIds': true},
    ),
    RecordFieldDefinition(
      id: 'narrativeTime',
      label: 'Narrative time',
      type: RecordFieldType.table,
      order: 110,
      extensionData: {'distinctFromWorldTime': true},
    ),
  ],
  sections: [
    RecordTemplateSection(
      id: 'temporal',
      title: 'Temporal',
      order: 10,
      fieldIds: [
        'eventType',
        'start',
        'end',
        'duration',
        'precision',
        'temporalStatus',
        'importance',
        'temporalScope',
        'dateRepresentations',
        'relativeDate',
        'narrativeTime',
      ],
    ),
  ],
  suggestedLinkTypeIds: [
    'partOf',
    'before',
    'after',
    'during',
    'contains',
    'overlaps',
    'concurrentWith',
    'causedBy',
    'leadsTo',
    'follows',
    'precedes',
    'repeats',
    'occursAt',
    'associatedWith',
    'involves',
    'relatedTo',
  ],
  builtIn: true,
  sourcePackId: 'authoros-core',
  permissions: {'editableDefinition': false},
  extensionData: {'timelineStudio': true, 'abstract': true},
);

const _calendar = RecordTypeDefinition(
  id: TimelineRecordTypes.calendarTypeId,
  name: 'Calendar Definition',
  description: 'A deterministic project calendar without Earth assumptions.',
  icon: 'calendar_month',
  categoryId: 'timeline',
  baseTypeId: 'general-lore',
  fields: [
    RecordFieldDefinition(
      id: 'months',
      label: 'Months',
      type: RecordFieldType.table,
      order: 100,
    ),
    RecordFieldDefinition(
      id: 'weekStructure',
      label: 'Week structure',
      type: RecordFieldType.table,
      order: 101,
    ),
    RecordFieldDefinition(
      id: 'yearLength',
      label: 'Year length',
      type: RecordFieldType.number,
      order: 102,
    ),
    RecordFieldDefinition(
      id: 'eraNames',
      label: 'Era names',
      type: RecordFieldType.list,
      order: 103,
    ),
    RecordFieldDefinition(
      id: 'epoch',
      label: 'Epoch',
      type: RecordFieldType.table,
      order: 104,
    ),
    RecordFieldDefinition(
      id: 'dateFormat',
      label: 'Date format',
      type: RecordFieldType.shortText,
      order: 105,
    ),
    RecordFieldDefinition(
      id: 'hasYearZero',
      label: 'Has year zero',
      type: RecordFieldType.boolean,
      order: 106,
    ),
    RecordFieldDefinition(
      id: 'yearDirection',
      label: 'Year direction',
      type: RecordFieldType.singleChoice,
      order: 107,
      options: ['forward', 'backward'],
    ),
    RecordFieldDefinition(
      id: 'conversionMetadata',
      label: 'Conversion metadata',
      type: RecordFieldType.table,
      order: 108,
    ),
  ],
  sections: [
    RecordTemplateSection(
      id: 'calendar',
      title: 'Calendar',
      order: 10,
      fieldIds: [
        'months',
        'weekStructure',
        'yearLength',
        'eraNames',
        'epoch',
        'dateFormat',
        'hasYearZero',
        'yearDirection',
        'conversionMetadata',
      ],
    ),
  ],
  suggestedLinkTypeIds: ['relatedTo'],
  builtIn: true,
  sourcePackId: 'authoros-core',
  permissions: {'editableDefinition': false},
  extensionData: {'timelineStudio': true, 'calendarDefinition': true},
);

const _timelineTypes = <String, String>{
  'timeline': 'Timeline',
  'timeline-era': 'Era',
  'timeline-age': 'Age',
  'timeline-historical-period': 'Historical Period',
  'timeline-event': 'Event',
  'timeline-event-group': 'Event Group',
  'timeline-date': 'Date',
  'timeline-date-range': 'Date Range',
  'timeline-milestone': 'Milestone',
  'timeline-turning-point': 'Turning Point',
  'timeline-historical-record': 'Historical Record',
  'timeline-war': 'War',
  'timeline-battle': 'Battle',
  'timeline-disaster': 'Disaster',
  'timeline-political-event': 'Political Event',
  'timeline-birth': 'Birth',
  'timeline-death': 'Death',
  'timeline-discovery': 'Discovery',
  'timeline-invention': 'Invention',
  'timeline-founding': 'Founding',
  'timeline-destruction': 'Destruction',
  'timeline-migration': 'Migration',
  'timeline-journey': 'Journey',
  'timeline-relationship-event': 'Relationship Event',
  'timeline-character-event': 'Character Event',
  'timeline-world-event': 'World Event',
  'timeline-custom-event': 'Custom Event',
};

const _icons = <String, String>{
  'timeline': 'timeline',
  'timeline-era': 'history',
  'timeline-event-group': 'account_tree',
  'timeline-war': 'shield',
  'timeline-battle': 'swords',
  'timeline-birth': 'child_care',
  'timeline-death': 'memorial',
  'timeline-journey': 'route',
};
